import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [users, setusers] = useState(null);
  const [search, setSearch] = useState("");

  useEffect(() => {
    fetch("https://randomuser.me/api/?results=100")
      .then((res) => res.json())
      .then((data) => {
        setusers(data);
      });
  }, []);

  console.log(users);
  console.log(search);

  return (
    <div className={styles.container}>
      <Head>
        <title>Fetch Api</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.search}>
          <label className={styles.labeltag1} htmlFor="name">
            Search Users
          </label>
          <input
            name="search"
            type="text"
            placeholder="e.g Bender Scarlet"
            onChange={(e) => setSearch(e.target.value)}
          />
          <label className={styles.labeltag2}>User List</label>
          <p className={styles.ptag}>
            Found 38 registered users from 2000 to 2020
          </p>
        </div>
        <div className={styles.box}>
          {users ? (
            users.results
              .filter((user) => {
                return search.toLowerCase() === ""
                  ? user
                  : user.name.title.toLowerCase().includes(search) +
                      user.name.first.toLowerCase().includes(search) +
                      user.name.last.toLowerCase().includes(search);
              })
              .map((user, main, key) => (
                <div key={main} className={styles.mainContainer}>
                  <img src={user.picture.thumbnail} />
                  <div className={styles.info}>
                    <div className={styles.name} key={key.name}>
                      {user.name.title} {user.name.first} {user.name.last}
                    </div>
                    <div key={key.date}>
                      Member since {}
                      {new Date(user.registered.date).getFullYear()}
                    </div>
                    <div key={key.country}>{user.location.country}</div>
                  </div>
                </div>
              ))
          ) : (
            <p>No users found</p>
          )}
        </div>
      </main>
    </div>
  );
}
